spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/orderdb  # URL подключения к базе данных orderdb
    username: postgres
    password: 35456156789Ghkl10aGhkl10a!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: order-service

server:
  port: 8083  # Порт, на котором работает Order Service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
